# Настройки словаря меток
dictionary: "DICT_APRILTAG_36h11"

# Якорная метка (к ней привязаны GPS координаты)
anchor_id: 0
anchor_gps:
  lat: 65.988106
  lon: 117.622628

# Размеры меток (в метрах)
# Для ROS-пайплайна все размеры задаются через config.
# Для SITL значения здесь должны совпадать с размерами в Gazebo.
default_marker_size: 0.3

# Список известных меток и их физические размеры
markers:
  - id: 0
    size: 0.05
  - id: 1
    size: 0.05
  - id: 2
    size: 0.05
  - id: 3
    size: 0.05
  - id: 4
    size: 0.05
  - id: 5
    size: 0.3
  - id: 6
    size: 0.3
  - id: 7
    size: 0.3
  - id: 8
    size: 0.3
  - id: 9
    size: 0.3
  - id: 10
    size: 1.5
  - id: 11
    size: 1.5
  - id: 12
    size: 1.5
  - id: 13
    size: 1.5
  - id: 14
    size: 1.5
  - id: 15
    size: 1.5
  - id: 16
    size: 1.5
  - id: 17
    size: 1.5
  - id: 18
    size: 1.5
  - id: 19
    size: 1.5
