markers:
  small:
    size: 50 # mm
    positions:
      tag_0: [0, 0]
      tag_1: [50, 50]
      tag_2: [50, -50]
      tag_3: [-50, 50]
      tag_4: [-50, -50]
  medium:
    size: 300 # mm
    positions:
      tag_5: [400, 0]
      tag_6: [0, 400]
      tag_7: [-400, 0]
      tag_8: [0, -400]
  large:
    size: 1500 # mm
    positions:
      tag_9: [4000, 4000]
      tag_10: [2000, 0]
      tag_11: [4000, -4000]
      tag_12: [0, 2000]
      tag_13: [0, -2000]
      tag_14: [-4000, 4000]
      tag_15: [-2000, 0]
      tag_16: [-4000, -4000]
      tag_17: [3000, -8000]
      tag_18: [-3000, -8000]
      tag_19: [0, 8000]
