tag_localizer:
  ros__parameters:
    map_frame: "map"
    camera_frame: "camera_optical_frame"
    base_link_frame: "base_link"
    markers:
      - '{"id": 0, "size_m": 0.05, "pose": [0.0, 0.0, 0.0012, 0.0, 0.0, 0.0]}'
      - '{"id": 1, "size_m": 0.05, "pose": [0.06, 0.0, 0.0012, 0.0, 0.0, 0.0]}'
      - '{"id": 2, "size_m": 0.05, "pose": [0.0, 0.06, 0.0012, 0.0, 0.0, 0.0]}'
      - '{"id": 3, "size_m": 0.05, "pose": [0.0, -0.06, 0.0012, 0.0, 0.0, 0.0]}'
      - '{"id": 4, "size_m": 0.05, "pose": [0.06, 0.06, 0.0012, 0.0, 0.0, 0.0]}'
      - '{"id": 5, "size_m": 0.20, "pose": [-0.125, 0.0, 0.0008, 0.0, 0.0, 0.0]}'
      - '{"id": 6, "size_m": 0.20, "pose": [0.375, 0.0, 0.0008, 0.0, 0.0, 0.0]}'
      - '{"id": 7, "size_m": 0.20, "pose": [-0.125, 0.5, 0.0008, 0.0, 0.0, 0.0]}'
      - '{"id": 8, "size_m": 0.20, "pose": [-0.125, -0.5, 0.0008, 0.0, 0.0, 0.0]}'
      - '{"id": 9, "size_m": 0.20, "pose": [0.375, -0.5, 0.0008, 0.0, 0.0, 0.0]}'
      - '{"id": 10, "size_m": 0.80, "pose": [-0.625, 0.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 11, "size_m": 0.80, "pose": [1.625, 0.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 12, "size_m": 0.80, "pose": [-2.875, 0.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 13, "size_m": 0.80, "pose": [-0.625, 1.5, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 14, "size_m": 0.80, "pose": [-0.625, -1.5, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 15, "size_m": 0.80, "pose": [-0.625, 3.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 16, "size_m": 0.80, "pose": [-0.625, 4.5, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 17, "size_m": 0.80, "pose": [-2.875, 6.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 18, "size_m": 0.80, "pose": [-0.625, 6.0, 0.0004, 0.0, 0.0, 0.0]}'
      - '{"id": 19, "size_m": 0.80, "pose": [1.625, 6.0, 0.0004, 0.0, 0.0, 0.0]}'
