tag_localizer:
  ros__parameters:
    map_frame: "map"
    camera_frame: "camera_link"
    base_link_frame: "base_link"
    markers:
      - '{"id": 6, "size_m": 0.04, "pose": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}'
      - '{"id": 0, "size_m": 0.20, "pose": [0.15, 0.0, 0.0, 0.0, 0.0, 0.0]}'
